name: ETL Pipeline

on:
  schedule:
  # cron to run everyday 5 pm
  - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  etl-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install pandas requests datetime

    - name: Run ETL script
      run: python etl_script.py
